version: '3'
services:
  primary:
    image: pihole/pihole:latest
    environment:
      WEBPASSWORD: primary_password1
  secondary:
    image: pihole/pihole:latest
    environment:
      WEBPASSWORD: secondary_password1
  orbital-sync:
    build:
      context: .
    depends_on:
      - primary
      - secondary
    environment:
      PRIMARY_HOST_BASE_URL: 'http://primary'
      PRIMARY_HOST_PASSWORD: 'primary_password1'
      SECONDARY_HOST_1_BASE_URL: 'http://secondary'
      SECONDARY_HOST_1_PASSWORD: 'secondary_password1'
      RUN_ONCE: 'true'
