version: '2.1'
services:
  primary:
    image: pihole/pihole:latest
    environment:
      WEBPASSWORD: primary_password1
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://primary/admin/']
      interval: 10s
      timeout: 10s
      retries: 5
  secondary:
    image: pihole/pihole:latest
    environment:
      WEBPASSWORD: secondary_password1
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://secondary/admin/']
      interval: 10s
      timeout: 10s
      retries: 5
  orbital-sync:
    build:
      context: .
    depends_on:
      primary:
        condition: service_healthy
      secondary:
        condition: service_healthy
    environment:
      PRIMARY_HOST_BASE_URL: 'http://primary'
      PRIMARY_HOST_PASSWORD: 'primary_password1'
      SECONDARY_HOST_1_BASE_URL: 'http://secondary'
      SECONDARY_HOST_1_PASSWORD: 'secondary_password1'
      RUN_ONCE: 'true'
