name: Bug or Other Issue
description: Get help with an issue or file a bug report
labels: ['triage']
assignees:
  - mattwebbio
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create an issue!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Or, what's the issue you're having? Also, what did you expect to happen?
      placeholder: A bug happened!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Orbital Sync are you running?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Please copy and paste any relevant log output from Orbital Sync. This will be automatically formatted, so no need for backticks.
      render: shell
