name: Prerelease

on:
  pull_request_target:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate tags
        id: docker_tags
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/mattwebbio/orbital-sync
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
          labels: ${{ steps.docker_tags.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm
